source: source

url: http://blog.samstokes.co.uk
title: Coding with Honour
subtitle: The personal blog of Sam Stokes.
author: Sam Stokes
permalink: /blog/:year/:month/:day/:title/

excerpt_separator: <!-- more -->
excerpt_link: Read on →

simple_search: http://google.com/search

plugins_dir: plugins

paginate: 10
paginate_path: /blog/page/:num/

gems:
  - jekyll-paginate

# Github repositories
github_user: samstokes
github_repo_count: 3
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: samstokes
twitter_widget_id: 442806389686038528

# Pinboard
pinboard_user: wibblefarmer
pinboard_count: 3
